# Site settings
title: Bugbox – Insect Vector Graphics
email: dariocorsi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A gallery of insect vector art. No spiders. To hell with spiders.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dariocorsi
github_username:  dariocorsi

# Build settings
markdown: kramdown
